
%% Statistical Pattern Recognition Software--by vahid asbaghi-- 1391--kntu
%--------------------------------------------------------------------------
function GUICHW1SPR
%% Grafical User Interface----
%
%% ************************************************************************
close all;
clear all;
clc;

%Controls Colors Define
panel_color=[0.55 0.75 0.65];
entryField_color=[1 1 1];
button_color=[0.4 0.4 0.9];
res_color=[0.2 0.2 0.3];

%% Handles and Controls Define
hFigure=figure(...
    'Units','Pixels',...
    'Position',[100 100 850 350],...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Color',[.5 .5 .5],...
    'Name','SPR Sofware--by Vahid Asbaghi--1391');


hPanel=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[0 0 400 350],...
    'BackgroundColor',panel_color);

hPanel11=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[400 0 225 350],...
    'BackgroundColor',[0.4 0.6 0.4]);
hpanel1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel11,...
    'Units','Pixel',...
    'Position',[0 330 220 17],...
    'String','Computer Homework 2 --- Bayes Classifier',...
    'BackgroundColor',[0.4 0.6 0.4]);
hButton1=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel11,...
    'Units','Pixels',...
    'Position',[20 300 100 20],...
    'String','Run-CHW2-Bayes',...
    'BackgroundColor',button_color,...
    'Callback',@Start_callback2);


hN=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 10 100 25],...
    'String','100',...
    'BackgroundColor',entryField_color);

hNl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 10 100 17],...
    'String','Number of samples',...
    'BackgroundColor',panel_color);

hit=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 40 100 25],...
    'String','10',...
    'BackgroundColor',entryField_color);

hitl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 40 100 17],...
    'String','Iterate number',...
    'BackgroundColor',panel_color);


hButton=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[5 70 100 20],...
    'String','Generate Samples',...
    'BackgroundColor',button_color,...
    'Callback',@Start_callback);

hPanel1=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[10 100 250 100],...
    'BackgroundColor',[0.5 0.5 0.5]);

hPanel2=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[10 220 250 100],...
    'BackgroundColor',[0.5 0.5 0.5]);

hp1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[270 150 100 17],...
    'String',': Mean estimations',...
    'BackgroundColor',panel_color);

hp2l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[270 250 120 17],...
    'String',': Covariance estimations',...
    'BackgroundColor',panel_color);

hp1ml=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 80 30 17],...
    'String','Means',...
    'BackgroundColor',panel_color);

hp1vl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 30 50 17],...
    'String','variance',...
    'BackgroundColor',panel_color);

hp2ml=uicontrol(...
    'Style','Text',...
    'Parent',hPanel2,...
    'Units','Pixel',...
    'Position',[10 80 30 17],...
    'String','Means',...
    'BackgroundColor',panel_color);

hp2vl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel2,...
    'Units','Pixel',...
    'Position',[10 30 50 17],...
    'String','variance',...
    'BackgroundColor',panel_color);

hp1m=uicontrol(...
    'Style','edit',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 60 100 17],...
    'BackgroundColor',[1 1 1]);

hp1v=uicontrol(...
    'Style','edit',...
    'Parent',hPanel1,...
    'Units','Pixel',...
    'Position',[10 10 220 17],...
    'BackgroundColor',[1 1 1]);

hp2m=uicontrol(...
    'Style','edit',...
    'Parent',hPanel2,...
    'Units','Pixel',...
    'Position',[10 60 220 17],...
    'BackgroundColor',[1 1 1]);

hp2v=uicontrol(...
    'Style','edit',...
    'Parent',hPanel2,...
    'Units','Pixel',...
    'Position',[10 10 220 17],...
    'BackgroundColor',[1 1 1]);
%%
hPanel12=uipanel(...
    'Parent', hPanel11,...
    'Units','Pixels',...
    'Position',[10 200 150 90],...
    'BackgroundColor',[0.6 0.6 0.6]);
hp12er1=uicontrol(...
    'Style','edit',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[5 5 50 17],...
    'BackgroundColor',[1 1 1]);
hp12er1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[60 5 50 17],...
    'String','class1',...
    'BackgroundColor',[0.6 0.6 0.6]);
hp12er2=uicontrol(...
    'Style','edit',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[5 25 50 17],...
    'BackgroundColor',[1 1 1]);
hp12er1l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[60 25 50 17],...
    'String','class2',...
    'BackgroundColor',[0.6 0.6 0.6]);
hp12ert=uicontrol(...
    'Style','edit',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[5 45 50 17],...
    'BackgroundColor',[1 1 1]);
hp12ertl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[60 45 50 17],...
    'String','total mis',...
    'BackgroundColor',[0.6 0.6 0.6]);
hp12ertl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel12,...
    'Units','Pixel',...
    'Position',[0 65 150 20],...
    'String','Number of Misclassification',...
    'BackgroundColor',[0.6 0.6 0.6]);
%%
hTBerr=uicontrol(...
    'Style','edit',...
    'Parent',hPanel11,...
    'Units','Pixel',...
    'Position',[135 175 50 17],...
    'BackgroundColor',[1 1 1]);
hTBerrl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel11,...
    'Units','Pixel',...
    'Position',[5 170 130 20],...
    'String','Theoretical Bayes Error=',...
    'BackgroundColor',[0.4 0.6 0.4]);
%%
hPanel13=uipanel(...
    'Parent', hPanel11,...
    'Units','Pixels',...
    'Position',[10 100 150 70],...
    'BackgroundColor',[0.6 0.6 0.6]);
hp13l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel13,...
    'Units','Pixel',...
    'Position',[0 45 150 20],...
    'String','Chernoff Analysis Result',...
    'BackgroundColor',[0.6 0.6 0.6]);
hch_opt=uicontrol(...
    'Style','edit',...
    'Parent',hPanel13,...
    'Units','Pixel',...
    'Position',[5 5 50 17],...
    'BackgroundColor',[1 1 1]);
hch_opt_l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel13,...
    'Units','Pixel',...
    'Position',[55 5 90 17],...
    'String','"s" optimal value',...
    'BackgroundColor',[0.6 0.6 0.6]);
hch_M_err=uicontrol(...
    'Style','edit',...
    'Parent',hPanel13,...
    'Units','Pixel',...
    'Position',[5 25 50 17],...
    'BackgroundColor',[1 1 1]);
hch_M_err_l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel13,...
    'Units','Pixel',...
    'Position',[55 25 90 17],...
    'String','Minimum Error',...
    'BackgroundColor',[0.6 0.6 0.6]);

%%
hPanel14=uipanel(...
    'Parent', hPanel11,...
    'Units','Pixels',...
    'Position',[10 5 150 90],...
    'BackgroundColor',[0.6 0.6 0.6]);
hp14l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel14,...
    'Units','Pixel',...
    'Position',[0 65 150 20],...
    'String','Max Bayes error',...
    'BackgroundColor',[0.6 0.6 0.6]);
hB_er=uicontrol(...
    'Style','edit',...
    'Parent',hPanel14,...
    'Units','Pixel',...
    'Position',[5 5 50 17],...
    'BackgroundColor',[1 1 1]);
hB_er_l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel14,...
    'Units','Pixel',...
    'Position',[55 5 90 17],...
    'String','Max error value',...
    'BackgroundColor',[0.6 0.6 0.6]);
hB_pw=uicontrol(...
    'Style','edit',...
    'Parent',hPanel14,...
    'Units','Pixel',...
    'Position',[5 40 50 17],...
    'BackgroundColor',[1 1 1]);
hB_pw_l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel14,...
    'Units','Pixel',...
    'Position',[55 25 90 40],...
    'String','value of P(w1) that maximize error',...
    'BackgroundColor',[0.6 0.6 0.6]);

%% computer HW3 Controls
hPanel_C3=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[625 0 225 350],...
    'BackgroundColor',panel_color);
hB_pw_l=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3,...
    'Units','Pixel',...
    'Position',[5 330 200 17],...
    'String','Computer Homework 3--KNN',...
    'BackgroundColor',panel_color);
hButton_C3=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel_C3,...
    'Units','Pixels',...
    'Position',[10 305 100 20],...
    'String','Run CHW3-KNN',...
    'BackgroundColor',button_color,...
    'Callback',@Start_CH3_callback);
hPanel_C3_1=uipanel(...
    'Parent', hPanel_C3,...
    'Units','Pixels',...
    'Position',[5 210 140 90],...
    'BackgroundColor',[0.6 0.6 0.6]);
ht_C3_1_head=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[5 65 120 20],...
    'String','Set Inputs for part #1',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_1_tr=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[5 45 50 17],...
    'String','50',...
    'BackgroundColor',[1 1 1]);
ht_C3_1_tr=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[55 40 70 20],...
    'String','N of trn smpls',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_1_tst=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[5 25 50 17],...
    'String','100',...
    'BackgroundColor',[1 1 1]);
ht_C3_1_tst=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[55 20 70 20],...
    'String','N of tst smpls',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_1_K=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[5 5 50 17],...
    'String','3',...
    'BackgroundColor',[1 1 1]);
ht_C3_1_K=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_1,...
    'Units','Pixel',...
    'Position',[55 0 70 20],...
    'String','value of K',...
    'BackgroundColor',[0.6 0.6 0.6]);

he_C3_1_out=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3,...
    'Units','Pixel',...
    'Position',[160 230 50 20],...
    'BackgroundColor',[1 1 1]);
ht_C3_1_out=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3,...
    'Units','Pixel',...
    'Position',[145 250 85 40],...
    'String','Mean Error Clasification Part#1:',...
    'BackgroundColor',panel_color);

%par#2 CHW3
hPanel_C3_2=uipanel(...
    'Parent', hPanel_C3,...
    'Units','Pixels',...
    'Position',[5 120 140 80],...
    'BackgroundColor',[0.6 0.6 0.6]);
ht_C3_2_head=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_2,...
    'Units','Pixel',...
    'Position',[5 55 120 20],...
    'String','Set Inputs for part #2',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_2_hN=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_2,...
    'Units','Pixel',...
    'Position',[5 40 50 17],...
    'String','0.2',...
    'BackgroundColor',[1 1 1]);
ht_C3_2_hN=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_2,...
    'Units','Pixel',...
    'Position',[55 35 60 20],...
    'String','set hN value',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_2_N=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_2,...
    'Units','Pixel',...
    'Position',[5 20 50 17],...
    'String','1500',...
    'BackgroundColor',[1 1 1]);
ht_C3_2_N=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_2,...
    'Units','Pixel',...
    'Position',[55 15 60 20],...
    'String','N of smpls',...
    'BackgroundColor',[0.6 0.6 0.6]);

% part3 CHW3
hPanel_C3_3=uipanel(...
    'Parent', hPanel_C3,...
    'Units','Pixels',...
    'Position',[5 40 140 70],...
    'BackgroundColor',[0.6 0.6 0.6]);
ht_C3_3_head=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_3,...
    'Units','Pixel',...
    'Position',[5 45 120 20],...
    'String','Set Inputs for part #3',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_3_K=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_3,...
    'Units','Pixel',...
    'Position',[5 30 50 17],...
    'String','20',...
    'BackgroundColor',[1 1 1]);
ht_C3_3_K=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_3,...
    'Units','Pixel',...
    'Position',[55 25 60 20],...
    'String','Set K value',...
    'BackgroundColor',[0.6 0.6 0.6]);
he_C3_3_N=uicontrol(...
    'Style','edit',...
    'Parent',hPanel_C3_3,...
    'Units','Pixel',...
    'Position',[5 5 50 17],...
    'String','2000',...
    'BackgroundColor',[1 1 1]);
ht_C3_3_N=uicontrol(...
    'Style','Text',...
    'Parent',hPanel_C3_3,...
    'Units','Pixel',...
    'Position',[55 0 60 20],...
    'String','N of smpls',...
    'BackgroundColor',[0.6 0.6 0.6]);

handles=[hFigure,hPanel,hPanel1,hp2v,hp2m,hp1v,hp1m,hButton,...
    hit,hN,hButton1,hp12ert,hp12er2,hp12er1,hTBerr,hch_opt,hch_M_err,...
    hB_pw,hB_er,hButton_C3,he_C3_1_tr,he_C3_1_tst,he_C3_1_K,...
    he_C3_1_out,he_C3_2_hN,he_C3_2_N,he_C3_3_K,he_C3_3_N];

set(handles,...
    'Units','Normalized'); %normalized position units: from (0,0) to (1,1)

%% Callbacks for Buttons

%callback for button
    function Start_callback(hObject,eventdata)
        
        sigma=[4,4;4,9];
        m=[1;3];
        %reading parameters
        it1=str2double(get(hit,'String'));
        N1=str2double(get(hN,'String'));
        
        
        [mm,sss,msighat,sigs,~]= SPR_CHW1(it1,N1,sigma,m);
        set(hp2v,'String',['[' num2str(sigs(1)) ',' num2str(sigs(2)) ' ; ' num2str(sigs(3)) ',' num2str(sigs(4)) ']']); %return evaluated values and show
        set(hp2m,'String',['[' num2str(msighat(1)) ',' num2str(msighat(2)) ' ; ' num2str(msighat(3)) ',' num2str(msighat(4)) ']']);
        set(hp1v,'String',[num2str(sss(1)) '  ' num2str(sss(2))]);
        set(hp1m,'String',[num2str(mm(1)) '  ' num2str(mm(2))]);
    end

    function Start_callback2(hObject,eventdata)
        %N=str2double(get(hN,'String'));
        N=str2double(get(he_C3_1_tst,'String'));
%         sigma1=[1,0.5;0.5,1];
%         sigma2=[1,-0.5;-0.5,1];
%         m1=[0;0];
%         m2=[0;0];
        sigma1=[0.2,0;0,0.2];
        sigma2=[0.2,0;0,0.2];
        m1=[1;1];
        m2=[1.5;1.5];
        % [mm,sss,msighat,sigs,x1]= SPR_CHW1(1,N,sigma1,m1);
        %[mm1,sss1,msighat1,sigs1,x2]= SPR_CHW1(1,N,sigma2,m2);
        x1=load('x1.mat');
        x2=load('x2.mat');
        x1=x1.x1_test;
        x2=x2.x2_test;
        figure;
        scatter(x1(:,1),x1(:,2),'*',...
            'MarkerEdgeColor','r');
        xlabel('x1')
        ylabel('x2');
        title('Test Samples and Bayes classifier red=class1');
        hold on;
        scatter(x2(:,1),x2(:,2),'*',...
            'MarkerEdgeColor','b');
        line([0,2.5],[2.5,0],'color',[0.1,0.7,0.7],'LineWidth',2);
        %line([-4,4],[0,0],'LineStyle','--','color',[0.1,0.7,0.7],'LineWidth',2);
        
        bound=2.5;
        cl=clas(x1,x2,bound);
        er1=0;
        er2=0;
        for i=1:N
            if cl(i,1)~=1
                er1=er1+1;
            end
            if cl(i,2)~=2
                er2=er2+1;
            end
        end
        er=er1+er2;
        set(hp12er1,'String',num2str(er1));
        set(hp12er2,'String',num2str(er2));
        set(hp12ert,'String',num2str(er));
        %set(hTBerr,'String',num2str(0.5));
        
        %OCC(x1,x2,N);
        %[opt_s,cher_err]=chernof(sigma1,m1,sigma2,m2);
        %set(hch_opt,'String',num2str(opt_s));
        %set(hch_M_err,'String',num2str(cher_err));
        
        %[mm,pwmax]=bayes_c(x1,x2,N);
        %set(hB_pw,'String',num2str(pwmax));
        %set(hB_er,'String',num2str(mm));
    end

%button CHW3 callback
    function Start_CH3_callback(hObject,eventdata)
        N=str2double(get(he_C3_1_tr,'String'));
        sigma1=[0.2,0;0,0.2];
        sigma2=[0.2,0;0,0.2];
        m1=[1;1];
        m2=[1.5;1.5];
        [mm,sss,msighat,sigs,x1]=SPR_CHW1(1,N,sigma1,m1);
        [mm1,sss1,msighat1,sigs1,x2]=SPR_CHW1(1,N,sigma2,m2);
        
        figure;
        hold on;
        scatter(x1(:,1),x1(:,2),'*',...
            'MarkerEdgeColor','r');
        line([0,2.5],[2.5,0],'color',[0.1,0.7,0.7],'LineWidth',2);
        xlabel('x1')
        ylabel('x2');
        title('Train Samples and Bayes classifier red=class1');
        scatter(x2(:,1),x2(:,2),'*',...
            'MarkerEdgeColor','b');
        w1=ones(50,1);
        x11=[x1 w1];
        w2=ones(50,1).*2;
        x22=[x2 w2];
        %tr1=kdtree([x11 ; x22],1);
        %save('tr1.mat','tr1');
        %save('tr2.mat','tr2');
        Ntst=str2double(get(he_C3_1_tst,'String'));
        [~,~,~,~,x1_test]=SPR_CHW1(1,Ntst,sigma1,m1);
        [~,~,~,~,x2_test]=SPR_CHW1(1,Ntst,sigma2,m2);
        save('x1.mat','x1_test');
        save('x2.mat','x2_test');
        K=str2double(get(he_C3_1_K,'String'));
        [nrst_nbr1,nrst_nbrv1]=KNN_KDTree(x1_test,K,[x11 ; x22]);
        [nrst_nbr2,nrst_nbrv2]=KNN_KDTree(x2_test,K,[x11 ; x22]);
        save('nrst_nbr1.mat','nrst_nbr1');
        save('nrst_nbr2.mat','nrst_nbr2');
        save('nrst_nbrv1.mat','nrst_nbrv1');
        save('nrst_nbrv2.mat','nrst_nbrv2');
        
        t_c1=0;
        t_c2=0;
        for i=1:length(nrst_nbrv1)
            l1=0;
            l2=0;
            for j=1:K
            if nrst_nbrv1{i,j}(1,3)==1
                l1=l1+1;
            end
            if nrst_nbrv2{i,j}(1,3)==2
                l2=l2+1;
            end
            end
            if l1>K/2
              t_c1=t_c1+1;
            end
            if l2>K/2
              t_c2=t_c2+1;
            end
        end
        er1=-t_c1+100;
        er2=-t_c2+100;
        save('er1.mat','er1');
        save('er2.mat','er2');
        set(he_C3_1_out,'String',num2str((er1+er2)/2));
        
        NN=str2double(get(he_C3_2_N,'String'));
        bound=[0,2];
        hn=str2double(get(he_C3_2_hN,'String'));
        phat=parzen(NN,bound,hn);
        figure;
        scatter(0:2/NN:2-2/NN,phat,'.');
        title(['parzen density function estimation hN = ' num2str(hn) ' and N = ' num2str(NN)]); 
        
        N=str2double(get(he_C3_3_N,'String'));
        K=str2double(get(he_C3_3_K,'String'));
        phat_KNN=knn_dens(N,K,bound);
        figure;
        scatter(0:2/N:2-2/N,phat_KNN,'.');
        title(['KNN density function estimation K = ' num2str(K) ' and N = ' num2str(N)]);
    end
%**************************************************************************
%***************************** END Function********************************
end
%**************************************************************************
%**************************************************************************