function GUI_SPR()
%% Grafical User Interface----
%
%
%% ************************************************************************
close all;
clear all;
clc;

%Controls Colors Define
panel_color=[0.5 0.5 0.8];
entryField_color=[1 1 1];
button_color=[0.7 0.7 0.4];

%% Handles and Controls Define
hFigure=figure(...
    'Units','Pixels',...
    'Position',[100 100 400 400],...
    'Toolbar','none',...
    'MenuBar','none',...
    'NumberTitle','off',...
    'Color',[.5 .5 .5],...
    'Name','New Grouping Genetic Algorithm');

hPanel=uipanel(...
    'Parent', hFigure,...
    'Units','Pixels',...
    'Position',[0 0 400 400],...
    'BackgroundColor',panel_color);

hPcil=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 350 30 25],...
    'String','Pci',...
    'BackgroundColor',panel_color);
hPciE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 355 70 25],...
    'String','0.9',...
    'BackgroundColor',entryField_color);
hPcfl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 320 30 25],...
    'String','Pcf',...
    'BackgroundColor',panel_color);
hPcfE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 325 70 25],...
    'String','0.4',...
    'BackgroundColor',entryField_color);
hPmil=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 290 30 25],...
    'String','Pmi',...
    'BackgroundColor',panel_color);
hPmiE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 295 70 25],...
    'String','0.1',...
    'BackgroundColor',entryField_color);
hPmfl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 260 30 25],...
    'String','Pmf',...
    'BackgroundColor',panel_color);
hPmfE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 265 70 25],...
    'String','0.35',...
    'BackgroundColor',entryField_color);
hPbil=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 230 30 25],...
    'String','Pbi',...
    'BackgroundColor',panel_color);
hPbiE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 235 70 25],...
    'String','0.08',...
    'BackgroundColor',entryField_color);
hPbfl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 200 30 25],...
    'String','Pbf',...
    'BackgroundColor',panel_color);
hPbfE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[285 205 70 25],...
    'String','0.04',...
    'BackgroundColor',entryField_color);
hPel=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[140 350 30 25],...
    'String','Pe',...
    'BackgroundColor',panel_color);
hPeE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[170 355 70 25],...
    'String','0.6',...
    'BackgroundColor',entryField_color);
hGenl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[140 320 30 25],...
    'String','Gen',...
    'BackgroundColor',panel_color);
hGenE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[170 325 70 25],...
    'String','30',...
    'BackgroundColor',entryField_color);
hPopl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[140 290 30 25],...
    'String','Pop',...
    'BackgroundColor',panel_color);
hPopE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[170 295 70 25],...
    'String','100',...
    'BackgroundColor',entryField_color);
hIslandl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[140 260 30 25],...
    'String','NOI',...
    'BackgroundColor',panel_color);
hIslandE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[170 265 70 25],...
    'String','5',...
    'BackgroundColor',entryField_color);
hNocl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 335 100 25],...
    'String','Number of Classes',...
    'BackgroundColor',panel_color);
hNocE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 315 85 30],...
    'String','0',...
    'BackgroundColor',entryField_color);
hNool=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 280 120 25],...
    'String','Number of Observation',...
    'BackgroundColor',panel_color);
hNooE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 260 85 30],...
    'String','0',...
    'BackgroundColor',entryField_color);


hButton1=uicontrol(...
    'Style','pushbutton',...
    'Parent',hPanel,...
    'Units','Pixels',...
    'Position',[5 365 110 30],...
    'String','Do Clustering',...
    'BackgroundColor',button_color,...
    'Callback',@Clustering_callback);

hSR=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 210 100 17],...
    'String','S-Index',...
    'Value',0,...
    'BackgroundColor',panel_color);
hDBR=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 190 100 17],...
    'String','DB-Index',...
    'Value',1,...
    'BackgroundColor',panel_color);
hEx1R=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[120 220 100 17],...
    'String','Firt Exper.',...
    'Value',1,...
    'BackgroundColor',panel_color);
hEx2R=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[120 200 100 17],...
    'String','Second Exper.',...
    'Value',0,...
    'BackgroundColor',panel_color);
hEx3R=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[120 180 100 17],...
    'String','Third Exper.',...
    'Value',0,...
    'BackgroundColor',panel_color);
hExnR=uicontrol(...
    'Style','Radio',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[120 160 100 17],...
    'String','New Exper.',...
    'Value',0,...
    'BackgroundColor',panel_color);


hselpix11=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[5 110 400 25],...
    'String','******************************** Results Section **************************************',...
    'BackgroundColor',panel_color);
hRl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 90 85 25],...
    'String','Rand Index',...
    'BackgroundColor',panel_color);
hRE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[10 70 85 30],...
    'String','0',...
    'BackgroundColor',entryField_color);
hNOCDl=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[110 90 140 25],...
    'String','Number of Class Determined',...
    'BackgroundColor',panel_color);
hNOCDE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[120 70 120 30],...
    'String','0',...
    'BackgroundColor',entryField_color);
hTimel=uicontrol(...
    'Style','Text',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 90 120 25],...
    'String','Time Consumption',...
    'BackgroundColor',panel_color);
hTimeE=uicontrol(...
    'Style','Edit',...
    'Parent',hPanel,...
    'Units','Pixel',...
    'Position',[250 70 120 30],...
    'String','0',...
    'BackgroundColor',entryField_color);
handles=[hFigure,hPanel,...
    hButton1];

set(handles,...
    'Units','Normalized'); %normalized position units: from (0,0) to (1,1)

%% Callbacks for Buttons

% Callback for button 'Do Clustering'
    function Clustering_callback(hObject,eventdata)
        tic();
        Pci=str2double(get(hPciE,'String'));
        Pcf=str2double(get(hPcfE,'String'));
        Pmi=str2double(get(hPmiE,'String'));
        Pmf=str2double(get(hPmfE,'String'));
        Pbi=str2double(get(hPbiE,'String'));
        Pbf=str2double(get(hPbfE,'String'));
        Pe=str2double(get(hPeE,'String'));
        Gen=str2double(get(hGenE,'String'));
        Pop=str2double(get(hPopE,'String'));
        n_island=str2double(get(hIslandE,'String'));
        n_class=str2double(get(hNocE,'String'));
        num=str2double(get(hNooE,'String'));
        S_ind=get(hSR,'Value');
        DB_ind=get(hDBR,'Value');
        Exp1=get(hEx1R,'Value');
        Exp2=get(hEx2R,'Value');
        Exp3=get(hEx3R,'Value');
        Expn=get(hExnR,'Value');
        
        if DB_ind==1
            method=1;
        elseif S_ind==1
            method=2;
        else
            method=1;
        end
        
        if Expn==1
            [R,NODC]=main_m3(n_class,num,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
        elseif Exp2==1
            if DB_ind==1
                [R,NODC]=main_m1(9,200,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            elseif S_ind==1
                [R,NODC]=main_m1(9,80,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            end
        elseif Exp1==1
            if DB_ind==1
                [R,NODC]=main_m(8,300,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            elseif S_ind==1
                [R,NODC]=main_m(8,100,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            end
        else
            if DB_ind==1
                [R,NODC]=main_m2(3,400,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            elseif S_ind==1
                [R,NODC]=main_m2(3,100,method,n_island,Pop,Gen,Pe,Pbf,Pbi,Pmf,Pmi,Pcf,Pci);
            end
        end
        time=toc();
        set(hRE,'String',num2str(R));
        set(hNOCDE,'String',num2str(NODC));
        set(hTimeE,'String',num2str(time));
    end


%**************************************************************************
%***************************** END Function********************************
end
%**************************************************************************
%**************************************************************************